### ISSUE TITLE
Converting from JavaScript values to RDF values and back

### ISSUE THREAD

**Issue by RubenVerborgh** [rdfjs/representation-task-force#17]

**Comment by RubenVerborgh** [comment]
Should be extensible to other types, like decimal.

**Comment by niklasl** [comment]
How about a simple `.toJSON()` method, equivalent to the XSD-based RDF-to-JSON conversion of JSON-LD? (See [JSON-LD Data Model](http://www.w3.org/TR/json-ld/#data-model) and [JSON-LD API RDF to Object Conversion](http://www.w3.org/TR/json-ld-api/#rdf-to-object-conversion).) This should be easy to keep consistent across implementations.

Then a `.toNative()` can be defined which is platform-specific and optionally extensible/customizable. I think at least this latter one belongs to an application layer though?

**Comment by elf-pavlik** [comment]
https://www.w3.org/TR/rdf-interfaces/#literals (*Datatype Map* section)

**Comment by bergos** [comment]
@niklasl I like `.toNative()`. Can you make a PR for it?

**Comment by RubenVerborgh** [comment]
@bergos Native has other connotations. (Native modules in Node.js.)

**Comment by bergos** [comment]
OK. Other proposals? We should avoid something like primitive, because maybe we want to extend this feature for other [datatypes](https://github.com/rdfjs/representation-task-force/issues/13).

**Comment by elf-pavlik** [comment]
I think that if we agree that we need a method on the Literal for that, we can nail down particular name already in the PR. I also think we could start with suggested .toJSON() and than see if we see need for .toNative() on this level as @niklasl suggested.

**Comment by wouterbeek** [comment]
How JavaScript values should be converted to-and-from RDF lexical forms has not been defined before IIANM.  To give a simple example: `x = Date.parse("-0000")` gives `NaN` but `-0000` does belong to the lexical space of `xsd:gYear`.  IOW, I cannot use off-the-shelf JavaScript Date to represent `xsd:dateTime` values.  Similar with `xsd:decimal` which should map to a pair of JavaScript integers (and not to float, as I've seen some SW practitioners do).

RDF Interfaces does not define these mappings either.  E.g., its `createLiteral` constructor already assumes we have a (String representing a) lexical form, whereas the difficult part is mapping JavaScript values to lexical forms.

JSON-LD only covers the simple cases, i.e., XSD Booleans, integers, floats and strings that can be mapped to-and-from JavaScript values quite easily.

**Comment by timbl** [comment]
The rdflib.js library accepts JS numbers and dates as input parameters as an alternative to rdf Literals, and converts them to Literals using Literal.fromValue
(This is a bit confusing as the word "value" here is being used for a native JS thing like a Date, where as a property of the Node it is the name given to a string.)

I think toNative() sounds like a good idea for the reverse direction.
What would it do with with a xsd:decimal -- return some decimal class or convert to float?

**Comment by timbl** [comment]
https://www.npmjs.com/package/decimal
I am a fan of Decimal by the way, from financial stuff.
I like and use all the time the fact that 22.45  in turtle is the decimal.
my Python code uses decimals.

**Comment by wouterbeek** [comment]
The use of JS floats for representing XSD decimals would indeed be a particularly bad design decision, since it would break the JS --|write|--> RDF --|read|--> JS loop.  Facilitating this loop within loss of information should be a design requirement IMO.

I don't see how rdflib.js is able to allow the creation of the `xsd:gYear` `-0000` from a JS date given that the JS `Date` object does not allow its construction.  I must admit that I have never used rdflib.js before, so I may be overlooking something here.  In general I expect there to be many small differences between JS and XSD datatypes that result either in loss of information (e.g., JS floats for XSD decimals) or loss of expressiveness (e.g., the inability to express the lexical year value `-0000`).

**Comment by dmitrizagidulin** [comment]
I think there's two main decisions to be made:

1. What should the to native JS and from native JS functions be named? There seems to be consensus around `.toNative()` (converting from Term to native JS). What about in the other direction?
2. How the XSD-to-JS conversions should be made.

It would be really helpful to at least standardize on the function names first, and then argue the actual details of conversion.

**Comment by wouterbeek** [comment]
@dmitrizagidulin I was indeed addressing (2) in my comments.  I see now that (1) is the actual topic of this issue, sorry for misreading/misinterpreting.

The mapping from lexical forms to values is called the *lexical mapping*, *lexical-to-value mapping* or *L2V* in the XSD 1.1 and RDF 1.1 specifications.  The mapping the other way round is called the *canonical mapping* (distinguished from the value-to-lexical mapping, which would map onto multiple representations for the same value, which leads to various problems in practice).

The name `.toNative()` would be a good name for an approximate mapping (i.e., one which loses information and/or expressiveness), because it makes explicit that it does not map a lexical form to a *value* but to a *native representation of a value* instead.

**Comment by bergos** [comment]
Closed based on the resolution in #136
