### ISSUE TITLE
.blankNode() should have an optional suggested label

### ISSUE THREAD

**Issue by bergos** [rdfjs/representation-task-force#30]
Usually blank nodes identifiers should be generated automatically, but in some cases (e.g. [Dataset Normalization](http://json-ld.github.io/normalization/spec/) it's a requirement to use a specific identifier.

**Comment by retog** [comment]
I think this should't be supported be supported at the model level as it brings aspects of concrete syntaxes (serializations) to the data model where it doesn't belong.

**Comment by bergos** [comment]
It's a requirement for the normalization and maybe other things we haven't thought about yet. We should mention that it could have drawbacks and it should only be used when it's required. But not supporting that feature means we rule out at least on usage and I expect signing graphs will become a big topic.

**Comment by retog** [comment]
While the algorithms to sign graphs I know about do assign a label to the blank nodes the signature is not dependent on  the label in that an isomorphic graph will alway lead to the same signature, the labeling is just an internal step of the algorithm. So a proper graph signature function `f` will return the same value for any isomorphic graph `G` regardless of blank node labels that may have been used in `G`. So as blank nodes are blank in RDF and as operations on graphs must return the same results on all isomorphic graphs (as they are necessarily semantically equal) having blank node labels in the API can be very confusing, things look different that are in fact equal. 

That json-ld normalization algorithm uses labels is not a reason to introduce them at an API level, other algorithms may color node or assign a weight to them, clearly we don't want to support colored and weighted nodes but stick with the concepts of the RDF model, the same goes for labels.

**Comment by dlongley** [comment]
@retog,

> That json-ld normalization algorithm uses labels is not a reason to introduce them at an API level, other algorithms may color node or assign a weight to them, clearly we don't want to support colored and weighted nodes but stick with the concepts of the RDF model, the same goes for labels.

In order to produce a signature, a serialization is required. If we are to permit signed datasets to be transported in a variety of syntaxes, a normalized serialization that they can be translated to is required. The simplest way to implement this is to use a serialization that uses blank node labels and to require the same blank node labels be used in the normalized version. Provided that the same normalization is used, the same labels should be output, regardless of the internals of the normalization algorithm.

If our intention is to pass the representation (per this API) of a dataset to a serializer, and there is no feature for a suggested blank node label, then serializers will need to be custom built or tightly integrated with normalization algorithms to produce the proper normalized serialization.

**Comment by retog** [comment]
@dlongley, a signature function and the converse verification function is an operation on the graph. The result must not be different based on some labels of the blank nodes. Internally such a signature function probably uses deterministic labeled blank nodes and a specific serialization. But having the actual model tainted by this label is not only bad design and my lead to confusion it is also of very little use:

- the labels assigned during a deterministic serialization become wrong as soon as a triple is added or removed from the graph
- if the signature function is tied to a serializer it can pass the labels either as a map, or thanks to the flexibility of js as a proprietary field of the node (it's a private thing between the signature algorithm and the specific serializer it uses)

There is also a little security issue: if a normalized graph gets modified the labels in the (now no longer normalized) graph can allow to guess the state before the changes to the graph, so the graph has to be skolemized or re-normalized in order not to give hints about the states of the graph before it was shared.

**Comment by dlongley** [comment]
@retog,

> a signature function and the converse verification function is an operation on the graph. The result must not be different based on some labels of the blank nodes. Internally such a signature function probably uses deterministic labeled blank nodes and a specific serialization. But having the actual model tainted by this label is not only bad design and my lead to confusion it is also of very little use

Agreed. I'm saying there's a use case, specifically for normalization algorithms, to be able to suggest blank node identifiers because implementers will want to reuse existing serialization libraries that use this API, not rewrite them.

> if the signature function is tied to a serializer it can pass the labels either as a map, or thanks to the flexibility of js as a proprietary field of the node (it's a private thing between the signature algorithm and the specific serializer it uses)

If we make a suggested blank node label part of this API, no specific serializer code is required.

> There is also a little security issue: if a normalized graph gets modified the labels in the (now no longer normalized) graph can allow to guess the state before the changes to the graph, so the graph has to be skolemized or re-normalized in order not to give hints about the states of the graph before it was shared.

This is something to be aware of. I don't know how common this scenario would arise in practice but the solution is easily implemented.

**Comment by dlongley** [comment]
I imagine there may be other use cases where people would like to be able to suggest to serializers the blank node labels to use. This is helpful for writing test tools, for example.

**Comment by retog** [comment]
@dlongley 

I understand the argument that existing serializer can be used by signing functions but this assumes that a serialization format is defined to deterministically produce the identical output given a labeling of the blank nodes. I think this is a very narrow usecase and far from outweighing the disadvantages.

Writing tests doesn't seem to be a good example for the feature to suggest blank node labels for the serializer to use, if it's just a suggestion the test shouldn't fail if its not there.

There might be more serialization hints one might want to give to a serializer, but a blank node identifier is much more problematic than such a hint. Without the identifier a blank node instance is the only instance representing a specific blank node, I can be sure that when I deal with a specific blank node I have the same object. This can be useful to many algorithms as it allows to add fields to the node (id, color, weight, smell). 

While some implementation might deal very efficiently with internalized strings so that they can compare as fast as object it is still faster to to compare blank nodes simply with `===` for equality, this is only possible without the identifiers.

My arguments also partially applies for removing the `.value` property from blank nodes, but without the ability to set the value and thus actually creating multiple instances representing the same blank node it is less problematic.

**Comment by RubenVerborgh** [comment]
Gents, thanks for the discussion, but we shouldn't overcomplicate things. Some people will like to give their blank node a label; that's a fairly common use case. So we just support it with a string argument.

I don't think there's need for more theory than that. This is for developers.

**Comment by dlongley** [comment]
@retog,

> I think this is a very narrow usecase and far from outweighing the disadvantages.

It is, but I was advocating specifically for that use case, I wasn't suggesting it was the only one. As I said in my other comment, people may want to suggest a blank node label. I understand that it isn't part of the abstract data model, but it is a useful feature.

**Comment by gkellogg** [comment]
RDF.rb allows labels for blank boxes, but note that a serializer needs to be wary about using these, as a graph may be composed of several different sources, that may overlap their label space. We do this by recording the label used with the actual BNode object and verifying that a BNode label always maps to the same object, and create a new one if necessary.

For a new architecture, probably best to not rely on regenerating the input labels. A strategy that allows labeling to be deferred, as json-ld does, might be more generically useful.

**Comment by ericprud** [comment]
I like the idea of the optimistic label reuse. It produces graphs that people can understand and encourages people to write more tests. In my experience, more tests rely on predictable bnode labels than rely and graph isomorphism, and I think we want to make testing as easy as possible, even if those tests end up overly intimate with the libraries.
