### ISSUE TITLE
Quad extends Triple

### ISSUE THREAD

**Issue by rubensworks** [rdfjs/representation-task-force#38]
The [interface spec figure](https://github.com/rdfjs/representation-task-force/blob/v0.1/interface-spec.md#data-interfaces) shows that Quad extends Triple.
However, In the description of Triple, it is said that Triple is an alias of Quad.
Wouldn't it therefore make more sense to let Triple extend from Quad?
Or am I missing something?

**Comment by RubenVerborgh** [comment]
The spec text is actually right here: we decided to make Triple an alias of Quad, so that there is no difference and that they can transition seamlessly.

It is thus the figure that should be adjusted.

**Comment by pieroit** [comment]
If we delete the extension arrow then we need a way to show the `alias` relation. I see two options:
- draw a single class with two names `Triple | Quad`. The problem is then that `.graph` has a predefined value only for Triple.
- another type of arrow? Can't find the UML notation for an alias.

**Comment by pieroit** [comment]
Today we discussed a little about this.
A proposal is to drop the ["Quad extends Triple"](https://github.com/rdfjs/representation-task-force/blob/master/interface-spec.md#quad-extends-triple) sentence in the spec as well as the "Triple" box in the [UML](https://github.com/rdfjs/representation-task-force/blob/master/interface-spec.md#data-interfaces), because we all agree on having Triple as an alias of Quad (no extension).

The factory methods signatures should be:
`.triple(Term, Term, Term): Quad`
`.quad(Term, Term, Term, Term): Quad`

Note that both return Quad (there is no Triple object, just a Quad with`.graph = DefaultGraph`) and Triple does not take the fourth argument, which is quite misleading.

Hope this is fine @bergos @elf-pavlik @dmitrizagidulin @RubenVerborgh
