### ISSUE TITLE
Proposal: Rename IRI node type to NamedNode

### ISSUE THREAD

**Issue by dmitrizagidulin** [rdfjs/representation-task-force#50]
Per yesterday's conversation on rdfjs public gitter channel -- Propose to rename the `IRI` node type on the [Data Interfaces spec](https://github.com/rdfjs/representation-task-force/blob/master/interface-spec.md) to `NamedNode` (to better match `BlankNode`).

**Comment by RubenVerborgh** [comment]
Thanks for creating this issue. There has been a long discussion about this in previous meetings, and we settled on IRI because this is the term actually used by developers. This is a library for developers, we should speak their language. (Summary of a very long discussion.)

Given that this discussion has been had previously, I'm hesitant to reopen this, unless there are new arguments. Could you link to / summarize the discussion on the gitter channel?

**Comment by RubenVerborgh** [comment]
See also #1 and reports of the first few meetings.

**Comment by timbl** [comment]
"this is the term actually used by developers"  -- but for something different!

**Comment by timbl** [comment]
Yes, I am sorry that the long email discussion on the list was decided to support "IRI".  I don't think the argument was that developers us it.   I thought that the prevailing reason was that the term "IRI" was used by the RDF 1.1 spec, and that spec carried a lot of weight.  Which is unfortunate, as I think it will confuse developers and was a mistake in the rdf1.1 spec.

**Comment by RubenVerborgh** [comment]
As far as I recall, the deciding argument was to make it easy for developers; the spec was one of the other reasons. If indeed the specifications themselves conflate (purposely, for simplicity) IRIs and named nodes, it's very hard to explain this to developers.

However, I agree the correct term is "named node" and that an IRI is just a string. Yet we should be able to point developers to a few official places where "named node" and IRI are used correctly; it would be hard to take the task upon ourselves to make that definition. So can we borrow the correct terminology from somewhere?

Also, we should remember that `iri` itself would only be used in very few places in any RDF/JS library. The interface name itself is never exposed; the only instances are `.termType` (which currently returns `"iri"`) and the constructor name. We could define an alias for the constructor name, so both `iri` and `namedNode` are support; we can, however, only define one return value for `.termType` (and `"iri"` is handy because it just has 3 letters).

**Comment by elf-pavlik** [comment]
I guess people developing for the web in JS may have some familiarity with https://nodejs.org/api/url.html

Thinking of graphs, traversing them, pattern matching etc. BlankNode and NamedNode make a lot of sense to me. On gitter chat we also had conversation around MergedNode which I understood could come handy to support owl:sameAs and allow a node to have many names - multiple IRIs. AFAIK among javascript implementations only rdflib.js has some support for reasoning. Personally, besides *owl:sameAs* I would like to ensure that we can implement in straight forward way at least *owl:inverseOf* and following [RDFa Vocabulary Entailment](https://www.w3.org/TR/rdfa-syntax/#s_vocab_entailment): *rdfs:subClassOf*, *rdfs:subPropertyOf*, *owl:equivalentClass*, *owl:equivalentProperty*.

Thinking of [skolemization](https://www.w3.org/TR/rdf11-concepts/#section-skolemization) it also sounds more natural to me that that a BlankNode becomes a NamedNode.

Since we talk about low level API intended for specific group of developers, we could prepare a poll and reach out to people who actively develop such libraries in javascript for feedback on this very concrete and well formulated question. I would also consider including in such poll topic of using uniform .value for all terms or .value / .uri / .id depending on particular type.

Last but not least, I would prefer to avoid deciding based on formal purism and approach it more in social way. Since rdflib.js stays under active development, I hope we can prioritise reaching agreement with people who actively commit to its code base.

> We could define an alias for the constructor name, so both iri and namedNode are supported; we can, however, only define one return value for .termType (and "iri" is handy because it just has 3 letters).

While I don't see 3 letters as an strong reason to choose it, I recognize that *IRI* gets used by [ jsonld.js and sparql query result json](https://github.com/rdfjs/representation-task-force/wiki/Existing-triple-and-quad-representations#node-types)

**Comment by elf-pavlik** [comment]
During call today we discussed difference between working with nodes of graph and working with identifiers. Current draft seems more in direction of working with identifiers - using **I**nternationalized **R**esource **I**dentifiers to identify a NamedNode and **B**lank **N**ode **I**dentifiers (currently referred to as blank nodes) to identify a BlankNode. While for NamedNode and BlankNode using IRI and BNI? seem straight forward, it doesn't seem to me that for Literal we can't simply talk about identifier... Also Variable seems more as just an identifier since .value refers to it's name and it doesn't really store any value.

also using common property *.value()* seems to make more sense for identifiers rather than nodes

**Comment by RubenVerborgh** [comment]
@elf-pavlik A literal is its own identifier.

**Comment by elf-pavlik** [comment]
I guess https://github.com/rdfjs/representation-task-force/issues/17 relates to that. We will never have case where Literal will have exactly the same .value but different dataType, or can we always infer the datatype just from .value?

Also exactly the same string can exist in two different languages e.g "stop*, we have two different terms with exactly the same .value - to identify them we seem to need your canonical representation https://github.com/rdfjs/representation-task-force/issues/7

**Comment by RubenVerborgh** [comment]
@elf-pavlik Datatype can never be inferred from `.value`, which is just a string. So when I say literal, I mean the whole literal, not just its string value.

**Comment by elf-pavlik** [comment]
so for IRI / NamedNode and BlankNode .value() refers to the actual identifier, while for Literal we have a different case and to get its **identifier** we use .... .toCanonical() ?

**Comment by RubenVerborgh** [comment]
Let's not overcomplicate :smile: IRI and BlankNode just happen to have a single kind of property involved; literal involves more properties (value / datatype / language).

My earlier comment was on the theoretical level, there is typically no actual need to obtain an identifier for a blank node. i.e.

> it doesn't seem to me that for Literal we can't simply talk about identifier...

Yes we can, on a theoretical level. On a practical level, you need to consider all properties of the literal (value / datatype / language), which `.toCanonical` does.

**Comment by elf-pavlik** [comment]
I started capturing notes on this wiki page https://github.com/rdfjs/representation-task-force/wiki/NamedNode

**Comment by elf-pavlik** [comment]
everyone please read @RubenVerborgh argument for IRI
https://github.com/rdfjs/representation-task-force/wiki/NamedNode#a-usage-based-argument-for-iri

@dmitrizagidulin @timbl

**Comment by gkellogg** [comment]
@rubenvervorgh's for BlankNode being the manifest label doesn't hold up, as if two graphs are merged, blank nodes with the same label aren't merged, as they are different modes, even if they are labeled the same in a concrete serialization used to instantiate the graph. A graph holds an abstract representation created by parsing a concrete representation into terms; blank node labels are just convenient for a concrete serialization, even if some vestige remains as a graph term.

You could make this argument about liberals and IRIs as well, but there is a 1-1 relationship there, so it is not ambiguous.

**Comment by RubenVerborgh** [comment]
@gkellogg The algorithm for merging two graphs is an independent matter. The difference between IRIs and blank node labels is that IRIs are universally valid, whereas blank node labels are only valid in a certain scope. Creating a new graph (through merging or otherwise) creates a new scope, hence new labels are necessary.

That does not change the fact that we interact with blank nodes through their concrete label, not though one of their many possible labels. To the best of my knowledge, there is no RDF implementation that allows blank nodes to have multiple labels.

**Comment by niklasl** [comment]
I think @RubenVerborgh's arguments for IRI are compelling, and reflect my own sentiments that this API deals with a concrete graph "depiction" and not its interpretation. Because of this, I do also think BlankNode ought to be called BlankNodeID, to avoid this confusion and stick to the symbols that denote, not the meaning that is denoted.

The NamedNode and BlankNode names suggest that these are both nodes (as in vertices in a graph, I suppose), in an expression existing "between" the concrete denoted form (representation) and the expressed resource relationships (intention). And that they are labelled with an IRI or a blank node identifier, respectively.

(Note that I definitely see value in an API that works on the expressed, "upper" level. In RDFLib, we added the [Resource class](https://rdflib.readthedocs.org/en/stable/_modules/rdflib/resource.html) quite some years ago to work with a more object-oriented form of the data, where the resource *has* an identifier, and properties (as in property-value pairs) accessible from it (outgoing and incoming). In JSON-LD, you get this form as well, as a tree of [nodes](https://www.w3.org/TR/json-ld/#node-objects). Admittedly, it is a rather "frozen" form. Nevertheless, the latter form is indexable and workable using functions to get a lot of usage for a fairly low amount of code. Programmers working like this stand the risk of not fully "getting" RDF though (although the notions aren't quite as muddied as they where by RDF/XML).)

At least, the story needs to be clear, with clear notions and abstractions. The case otherwise tends to encourage a bunch of "mights" and "would be nice" features at levels lower down than they should be to keep things simple.
