### ISSUE TITLE
Add a method for representing Nodes (and Triples/Quads) in a canonical way

### ISSUE THREAD

**Issue by bergos** [rdfjs/representation-task-force#7]
The purpose of this method is to obtain a unique String representation of a Node, such that each Node corresponds to exactly one String representation, and that all Nodes created by converting the String representation are `.equal` to each other.

**Comment by RubenVerborgh** [comment]
To be discussed:
- the name of this method (`.toCanonical` has been suggested)
- the value of this method

For the value, we should especially ensure that:
- IRIs and literals with the same value have a _different_ canonical representation
- equality is not influenced by escape sequences or encodings

**Comment by RubenVerborgh** [comment]
I have good experience with the [canonical representation of N3.js](https://github.com/RubenVerborgh/N3.js#utility) (that also happens to be the main representation there). It works as follows:

- The canonical representation of a **named node** is the string value of its IRI.
  - example: `var x = 'http://example.org/foo#bar'`
- The canonical representation of a **blank node** is the name of that node preceded by `_:`.
  - example: `var x = '_:abc2'`
- The canonical representation of a **variable** is the name of that node preceded by `?`.
  - example: `var x = '?person'`
- The canonical representation of a **literal** is the unescaped string value of that literal, surrounded by double quotes (`""`). If the literal has a language, append `@` and the string value of that language. Otherwise, if the literal has a specific type, append `^^` and the string value of its IRI. 
  - example: `var x = '"string value"'`
  - example: `var x = '"string value"@en'`
  - example: `var x = '"string value"^^http://example.org/foo#type'`
  - example: `var x = '"string value with a quote " and newline \n inside"'`
  - example: `var x = '"http://example.org/foo#bar"'`

Note in particular that:
- the type of the represented node is determined by its first character (`_`, `?`, `"`, or anything else)
- IRIs and literals with the same value have different canonical representations (`'http://example.org/foo#bar'` versus `'"http://example.org/foo#bar"'`)
- literals are _not_ Turtle representation, since no escaping happens

N3.js chooses not to have any special marker around IRIs (like `<`) because a) it is not necessary as a distinguishing characteristic, because the others already have these, and b) IRIs are the most common type of node, so they should be the easiest to represent: literals use special characters, but IRIs do not.

The canonical representation of N3.js _could_ be an inspiration for what we will design.

**Comment by l00mi** [comment]
@RubenVerborgh I now you did also some performance tests regarding this representation in JavaScript engines. Do you have pointer to this tests which might support this format?

**Comment by RubenVerborgh** [comment]
Yes, but they tested how engines performed if they used this as their actual _interface_. I would expect/hope the `.toCanonical` method to be used for debugging purposes mostly (or for hashing).

https://github.com/RubenVerborgh/TripleRepresentationBenchmark

**Comment by bergos** [comment]
The 1.1. version of the N-Triples spec contains now a section ["A Canonical form of N-Triples"](https://www.w3.org/TR/n-triples/#canonical-ntriples). I would propose to use that form. It's only defined for triples, but can be easily extended for quads. It will be also [used](https://lists.w3.org/Archives/Public/public-rdfjs/2016Jan/0012.html) by the [RDF Dataset Normalization](http://json-ld.github.io/normalization/spec/) and I expect it would be also the first choice for other standards that require a canonical serialization.

**Comment by RubenVerborgh** [comment]
Sounds good to me. Then the escaping scenarios are also limited. We should just add an extra case for variables.

**Comment by bergos** [comment]
[Here](https://github.com/rdfjs/representation-task-force/pull/24) is the PR.

**Comment by l00mi** [comment]
29.01.2016 meeting resolved by PR
