### ISSUE TITLE
Should Literal.datatype be an IRI (string) or a NamedNode?

### ISSUE THREAD

**Issue by RubenVerborgh** [rdfjs/representation-task-force#93]
As mentioned in #92, we should decide whether we want `Literal.datatype` to be an IRI (string) or a NamedNode.

For clarity, here are the definitions:
- an IRI is a string
- `NamedNode` is the RDF/JS interface to represent nodes identified by an IRI

The spec currently states:

> `IRI .datatype` the datatype of the literal

Given the definitions above, there are two possible corrections for this:

- `string .datatype` the IRI of the literal (vote with “thumbs up”)
- `NamedNode .datatype` a named node representing the IRI of this literal  (vote with “laugh”)

**Comment by RubenVerborgh** [comment]
I voted for `string .datatype`, because it doesn't require an extra object (faster comparisons, easier to traverse).

**Comment by elf-pavlik** [comment]
Doesn't this one duplicate https://github.com/rdfjs/representation-task-force/issues/83 ?

It looks like in that one two people voted 😆

**Comment by RubenVerborgh** [comment]
No, #83 was about the constructor.

**Comment by elf-pavlik** [comment]
I understand that you prefer that constructor requires a Term (NamedNode) but .datatype stores a plain string? Not sure if that wouldn't cause confusion but people who currently implement this spec should decide!

**Comment by RubenVerborgh** [comment]
> I understand that you prefer that constructor requires a Term (NamedNode)

I agreed with @blake-regalia in #83 that the Literal constructor had no way to differentiate whether `languageOrDatatype` was a language or a data type.

Whether `NamedNode` is the ideal solution is something else.

> but .datatype stores a plain string?

That's what this PR is about indeed. Let's first see what is the most logical for `.datatype`; we can then see if the constructor should be aligned later on.

**Comment by elf-pavlik** [comment]
I added 👍 
IMO Term shouldn't have another Term as value of its property, all other values require `string` and Term here would make an exception...

**Comment by blake-regalia** [comment]
I understand the convenience of having the IRI one property accessor away (i.e., `.datatype` being a `string`). But if you think in terms of allocation, `string` actually requires a much larger memory footprint because it is a native datatype so it is pass-by-value (i.e., every assignment of a property to a string value *copies* the original value, allocating new memory each time). Therefore, every literal's `.datatype` would require its own chunk of memory.

On the other hand, if you use `Term`, the implementation can reuse the same datatype object (e.g., `NamedNode 'xsd:integer'`) many many times over without consuming nearly as much memory because `object`s are pass-by-reference.

**Comment by RubenVerborgh** [comment]
> Therefore, every literal's .datatype would require its own chunk of memory.

Incorrect. First, this doesn't hold in general, as `.datatype` can be implemented ways that do not use any extra fields ([example](https://github.com/RubenVerborgh/N3.js/commit/bd5f7fbb6c5c609a5e3d458acbdc4a71b8deef44#diff-e4f1532d47adaadf2d6a59fe47e2384cR99)). Second, I'm pretty sure V8 optimizes for this and does not duplicate an identical string every time.

**Comment by blake-regalia** [comment]
> First, this doesn't hold in general, as .datatype can be implemented ways that do not use any extra fields (example).

I'm pretty sure that entirely depends on the implementation. In n3.js, you are already storing the datatype IRI as a string (within the canonical form) for each and every Literal, so there is no string interning happening there anyway. Also, that getter method creates a new string every time it is called. This will likely bog down GC when searching the store for a Literal of a certain datatype since it will create, compare, then discard a new string every time. The point is that although n3.js's implementation clearly has a strong benefit for storing each Literal in canonical form (e.g., for Term equality comparison), this was a design choice and the reasons for using datatype as a `string` only seem to benefit this specific flavor of an implementation.

**Comment by RubenVerborgh** [comment]
> I'm pretty sure that entirely depends on the implementation. 

Exactly, that was my point :wink:

> This will likely bog down GC when searching the store for a Literal of a certain datatype since it will create, compare, then discard a new string every time.

Sure, but that's about N3.js.

> the reasons for using datatype as a string only seem to benefit this specific flavor of an implementation

Note that there are other reasons for using a datatype as string, as stated by @elf-pavlik and myself above.

**Comment by elf-pavlik** [comment]
I believe two of you can come up with some benchmarks which will help base this decision in science :) (I removed my 👍 and rather abstain here)

IMO LowLevel API should prioritize performance event if it will require compromising the principle of least surprise. And again I see both of you very qualified to figure out all the performance impacts of both approaches.

**Comment by RubenVerborgh** [comment]
@elf-pavlik Will look into creating a proper benchmark for this; but honestly, I'm not sure whether you (or anybody) should abstain here. My initial question was also focused on usage: what developers think is a convenient way to use a library.

**Comment by bergos** [comment]
We had already an issue for this topic #78

**Comment by blake-regalia** [comment]
@bergos 
> We had already an issue for this topic #78

This is true. I did bring up this exact issue in #78, but have since changed my position! LOL :P

@elf-pavlik 
> I believe two of you can come up with some benchmarks which will help base this decision in science

I agree.

@RubenVerborgh 
> My initial question was also focused on usage: what developers think is a convenient way to use a library

This is also very important, which is why I think we should organize the pros / cons of each and provide a comprehensive comparison before committing to one or the other since this would be a confusing & breaking API change if we changed our mind in the future.

**Comment by bergos** [comment]
We discussed this topic already and we agreed on `NamedNode` (we forgot to replace `IRI` with `NamedNode`, but it would be `string` otherwise).

- Consistency: The other properties are strings, because of the mapping of the RDF Spec to JS types. Using `NamedNode` whenever there is a `NamedNode` would be more consistent.

- CURIE support: If we add CURIE support with the high level API, we can use resolve or reduce.

- Other `NamedNode` methods: Maybe we will add some other methods with the high level API for `NamedNode`, which we don't have in mind now.

- Performance: It can be implemented without performance drawbacks and the implementation will be still super simple. If we use `string` we must rely on the JS engine (don't forget embedded devices!).

**Comment by RubenVerborgh** [comment]
All right, I follow all arguments and will implement #92 with the resolution from #78. Just two questions:

- Did sufficient people vote/agree (for posterior reference; #78 only has 2 participants)?

- Would CURIE support in the high-level API affect the low-level API in any way? I.e., can or can't we assume that `NamedNode#value` is always an absolute, unabbreviated IRI?

**Comment by elf-pavlik** [comment]
> Would CURIE support in the high-level API affect the low-level API in any way? I.e., can or can't we assume that NamedNode#value is always an absolute, unabbreviated IRI?

👍 to write it in such explicit way in definition of NamedNode#value

When it comes to assuming, we discussed that libraries can produce non-valid terms and one needs consider validations independently #57 

As I understand graphy.js parser doesn't validate if named nodes have valid IRIs so if source has invalid IRIs it will produce named node with invalid IRI https://github.com/blake-regalia/graphy.js#performance

**Comment by bergos** [comment]
> Did sufficient people vote/agree (for posterior reference; #78 only has 2 participants)?

We discussed this in a meeting, but I didn't find anything in the wiki. Blame says you [changed it](https://github.com/rdfjs/representation-task-force/commit/bea9407ba8e8ed58b86a7e7d93c0c169207d2896), so you should know better than me ;-)

> Would CURIE support in the high-level API affect the low-level API in any way? I.e., can or can't we assume that NamedNode#value is always an absolute, unabbreviated IRI?

The high level API should just add new features in a compatible way (we will add this to the mission statement of the high level API). The high level factory or another method/function should expand the CURIE. An implementation could also store the CURIE in a term and expand it in a `.value` getter. Should we write this down somewhere? But we should avoid mixing this with validation. Validation can be a library feature, but should not be part of the spec.

**Comment by RubenVerborgh** [comment]
@bergos I've reopened #78, as I'm unsure the arguments have sufficiently been discussed.

Playing the devil's advocate here, but it seems that each of the arguments you listed has a counterargument:

> Consistency: The other properties are strings, because of the mapping of the RDF Spec to JS types. Using NamedNode whenever there is a NamedNode would be more consistent.

An equally valid argument for consistency would be "strings, because the others are strings".

Also, "whenever there is a NamedNode" => but _is_ the type really a named node, or just an IRI?

> CURIE support: If we add CURIE support with the high level API, we can use resolve or reduce.

But according to @elf-pavlik, this wouldn't change the low-level interface.

> Other NamedNode methods: Maybe we will add some other methods with the high level API for NamedNode, which we don't have in mind now.

Agree on that one then, but again, _is_ type really a named node? (The RDF 1.1 spec doesn't really help here, as we know from experience with the IRI / named node distinction.)

> Performance: It can be implemented without performance drawbacks

This has not been evaluated, so we don't know. I expect that the different solutions will each have their performance advantages and disadvantages in different scenarios.

----

 > Blame says you changed it, so you should know better than me ;-)

Ah, but that was back when we didn't distinguish between IRIs (strings) and blank nodes :wink: (Honestly, I can't remember.)

----

I propose to collect arguments pro and contra in #78.
